version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/tuan.conf:/etc/nginx/conf.d/default.conf
        links:
            - php:php
    php:
        image: php:5-fpm
        volumes:
            - ./html:/var/www/html
